CREATE TABLE `snuid` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`snuid` VARCHAR(32) NOT NULL,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	INDEX `created` (`created`)
)
COMMENT='39B745681A1F68924BEFF7F21B62E236'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB;